export const testData = [
  {
    id: 1,
    status: "Active",
    client: "Client A",
    loading: "Yes",
    unloading: "No",
    typeCargo: "Type X",
    executor: "John Doe",
    numberCar: "ABC123",
    driver: "Jane Smith",
    cost: "$500",
  },
  {
    id: 2,
    status: "Inactive",
    client: "Client B",
    loading: "No",
    unloading: "Yes",
    typeCargo: "Type Y",
    executor: "Bob Johnson",
    numberCar: "DEF456",
    driver: "Mike Davis",
    cost: "$700",
  },
];
